import{a as v,i as h,S as L}from"./assets/vendor-D73Uttp0.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();let d="",u=1;const E=40;document.getElementById("load").style.display="none";document.getElementById("search-images").addEventListener("input",o=>{d=o.target.value,console.log(d),d===""?document.getElementById("button-search").setAttribute("disabled",!0):document.getElementById("button-search").removeAttribute("disabled")});document.getElementById("button-search").addEventListener("click",()=>{d.trim()!==""&&(u=1),document.getElementById("gallery").innerHTML="",I(d)});d="";let y;async function I(o){const t=`https://pixabay.com/api/?key=46148629-af6e53c51d7dfe0604412e9db&q=${encodeURIComponent(o)}&image_type=photo&per_page=${E}&page=${u}`;try{const a=await v.get(t);y=a.data.totalHits;const e=a.data.hits;if(y===0){h.show({title:"No Images",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3,color:"warning"}),document.getElementById("load").style.display="none";return}b(e)}catch(a){console.log("Photos can't taken"),h.error({title:"Error",message:a.message,position:"topRight"})}console.log(`Current Page: ${u}, Per Page: ${E}, Total Hits: ${y}`)}function w(o){u*E>=o?(document.getElementById("load").style.display="none",h.show({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3,color:"info"})):document.getElementById("load").style.display="block"}document.getElementById("load").addEventListener("click",()=>{u++,I(d),console.log("load buttona tıkladım")});function b(o){document.getElementById("image-results");const l=document.getElementById("gallery"),t=document.getElementById("load");t&&t.remove(),o.forEach(e=>{const n=document.createElement("img");n.src=e.webformatURL,n.alt=e.tags,n.dataset.source=e.largeImageURL;const c=document.createElement("a");c.classList.add("link-a"),c.href=e.largeImageURL,c.setAttribute("data-lightbox","gallery"),c.appendChild(n);const i=document.createElement("li");i.classList.add("image-list"),i.appendChild(c);const s=document.createElement("div");s.classList.add("image-info");const p=document.createElement("p");p.innerHTML=`<div class="notes">
        <p class="foto-note" id="likes">Likes</p>
        <p>${e.likes}</p>`;const g=document.createElement("p");g.innerHTML=`<div class="notes">
        <p class="foto-note" id="views">Views</p>
        <p>${e.views}</p>`;const m=document.createElement("p");m.innerHTML=`<div class="notes">
        <p class="foto-note" id="comments">Comments</p>
        <p> ${e.comments}</p>
        </div>`;const r=document.createElement("p");r.innerHTML=`<div class="notes">
        <p class="foto-note" id="download">Downloads</p>
        <p>${e.downloads}</p>
        </div>`,s.appendChild(p),s.appendChild(g),s.appendChild(m),s.appendChild(r),i.appendChild(s),l.appendChild(i),document.body.appendChild(l)}),new L("#gallery a",{captionsData:"alt",captionDelay:250}),document.getElementById("image-results").appendChild(t),S(),w(y)}function S(){const o=document.querySelectorAll(".link-a");let l=null,t=0;o.forEach((a,e)=>{a.addEventListener("click",n=>{if(n.preventDefault(),t=e,n.target.nodeName!=="IMG")return;const c=a.getAttribute("href"),i=a.querySelector("img").alt,s=new L({items:[{src:c,alt:i},...Array.from(o).map(r=>({src:r.getAttribute("href"),alt:r.querySelector("img").alt}))],captionsData:`${i}`,captionDelay:250});s.showModal(),l=s,s.on("show.simplelightbox",()=>{s.select(t)});const p=s.element().querySelector("#prev"),g=s.element().querySelector("#next");p.addEventListener("click",()=>{t=t>0?t-1:o.length-1,updateModal(s,o[t]);const r=o[t].querySelector("img").dataset.source,f=o[t].querySelector("img").alt;s.element().querySelector("img").src=r,s.element().querySelector("img").alt=f}),g.addEventListener("click",()=>{t=t<o.length-1?t+1:0,updateModal(s,o[t]);const r=o[t].querySelector("img").dataset.source,f=o[t].querySelector("img").alt;s.element().querySelector("img").src=r,s.element().querySelector("img").alt=f});const m=r=>{(r.key==="Escape"||r.key==="Esc")&&l&&(l.close(),document.removeEventListener("keydown",m),l=null)};document.addEventListener("keydown",m)})})}
//# sourceMappingURL=index.js.map
